name: ecommerce_platform_crio_do
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^0.3.7
  carousel_pro: ^1.0.0
  floating_action_bubble: 1.0.9
  flutter_speed_dial: ^2.1.1
  google_fonts: ^1.1.2
  flutter_icons: ^1.1.0
#  english_words: ^3.1.0
#  carousel_pro: ^1.0.0
#  firebase_auth: ^0.16.0
#  shared_preferences: ^0.5.7
#  firebase_core: ^0.4.4+3
#  firebase_analytics: ^5.0.15
#  cloud_firestore: ^0.13.5
#  firebase_storage: ^3.1.6
#  firebase_messaging: ^6.0.16
#  google_sign_in: ^4.4.4
#  photo_view: ^0.9.2
#  cached_network_image: ^2.2.0+1
#  flutter_spinkit: "^4.1.2"
#  fluttertoast: ^4.0.0
#  location: ^3.0.2
#  google_maps_flutter: ^0.5.27+3
#  geocoder: ^0.2.1
#  provider: ^4.1.2
#  geolocator: ^5.3.1
#  geoflutterfire: ^2.1.0
#  flutter_speed_dial: ^1.2.5
#  url_launcher: ^5.4.10
#  image_picker: ^0.6.7
#  webview_flutter: ^0.3.22+1
#  badges: ^1.1.1
#  flutter_signin_button: ^1.0.0
#  curved_navigation_bar: ^0.3.2
#  streaming_shared_preferences: ^1.0.1
#  line_awesome_icons:
#    git:
#      url: git://github.com/mateotomasgomez/line_awesome_icons_flutter.git
#      ref: master



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/fresh.jpg
    - images/shitts.jpg
    - images/orders.webp
    - images/cart.jpg
    - images/perfume.jpg
    - images/dress.jpg
    - images/heels.jpg
    - images/shoes.jpg
    - images/sneaker.jpg
    - images/reddress.jpg
    - images/whitedress.jpg
    - images/tshirt.jpg
    - images/dress2.jpg
    - images/heel2.png
    - images/earrings.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
